AOEpeople/techradar

- radar/2021-01-01/nx.md
> Add NX to tools quadrant

- radar/2021-01-01/drupal.md
> Add Drupal to tools quadrant

- radar/2021-01-01/docker.md
- radar/2021-01-01/oci-container.md
deprecate "Docker" and promote OCI-compatible containers
> OCI containers

- radar/2021-01-01/tailwindcss.md
New article. Please read and support e.g. with a better translation/wording
> Radar 2021 01 01 tailwind css

- radar/2021-01-01/artifactory.md
> Fade out Artifactory

- radar/2021-01-01/postman.md
> Adopt + fade out postman

- radar/2022-03-28/crc.md
- radar/2022-03-28/evil-user-stories.md
- radar/2022-03-28/rabbitmq.md
- radar/2022-03-28/rest-assured.md
- radar/2022-03-28/sitespeed.md
I've bundled the fadeouts I'm responsible for into this PR with individual commits each. Not sure if this is of any use or if we should rather squash into a single commit though.
> fadeouts (RabbitMQ, REST Assured, Sitespeed.io, CRC Games, Evil User Stories)

- radar/2022-03-28/container-based-builds.md
- radar/2022-03-28/jaeger.md
- radar/2022-03-28/packer.md
Fading out Packer, Jaeger and Container based builds
> fade out multiple tools

- package.json
- yarn.lock
Needs to be updated to v3.2.0 once released
https://github.com/AOEpeople/aoe_technology_radar/pull/130
Resolves #70
> chore(deps): update techradar to most recent version

- public/messages.json
We removed AOE communication aspect.
The quadrant focuses on general Platform, Operational, Infrastructure technologies
> Update description for platform quadrant

- radar/2022-03-28/scala-lang.md
- radar/2022-03-28/scala3.md
It's written from the Omnevo POV but I think that's ok although Scala is not used at AOE.
> feat: fade out scala-lang and move scala3 to adopt

- radar/2022-10-12/specflow.md
refs: Add? [framework][asses] SpecFlow (204)
> docs: add specflow

- radar/2022-10-12/playwright.md
- update description
- change ring from assess to trial
- change quadrant to languages and frameworks
refs: Update [tools->framework][trial] Playwright (194)
> docs: update playwright details

- radar/2022-10-12/ansible.md
refs: Add [platforms][trial] ansible (190)
> docs: Add ansible

- radar/2022-10-12/flutter.md
As requested i have added some new documentation for Flutter.
> documentation: added Flutter

- Readme.md
> Fix PUBLIC_URL in run docs

- radar/2023-09-01/vite.md
Adding Vite as a new tool that is recommended to use in new projects.
> docs: add vite to adopt

- radar/2023-09-01/design-system.md
As we could prove that Design Systems work, we recommend using it.
> docs: update Design System to adopt

- radar/2023-09-01/diagrams-as-code.md
Adding some mentionable tools for diagramming in code.
> docs: update Diagrams as Code

- radar/2023-09-01/vue.md
Updated the Vue description to match newer Vue versions.
This is committed by Felix Ruf
> feat(vue): update vue description

- radar/2023-09-01/angular.md
> docs: update angular

- radar/2023-09-01/jest.md
Hello,
with this small merge request jest won't be featured anymore.
thanks
Dennis Ludwig
> feat(jest): fade out jest in v7

- radar/2023-09-01/css-in-js.md
With this merge request i would like to reflect on the latest developments in the css-in-js libraries because of the arrival of react 18.
Thanks
Dennis Ludwig
> feat(css-in-js): update description to reflect latest developments

- radar/2023-09-01/react.md
An update for React to reflect new features.
> docs: update react

- radar/2023-09-01/next-js.md
Update the NextJS blib to reflect new features that came with the latest version.
> docs: update next

- radar/2019-11-01/blameless-post-mortems.md
- radar/2023-11-01/blameless-post-mortems.md
and emphasize the matter of trust in the description
> blameless post mortems to adopt

- radar/2024-06-01/open-api.md
Streamlined the OpenAPI description and removed the old v2 references, added a caption for TMForum OpenAPIs.
> feat: add TMForum OpenAPIs to OpenAPI

- radar/2024-06-01/apm.md
> docs: fade out application performance management

- radar/2024-06-01/ports-and-adapters.md
> docs: fade out ports and adapters

- radar/2024-06-01/gitflow.md
> docs: fade out gitflow

- radar/2024-06-01/falco.md
> docs: fade out falco

- radar/2024-06-01/apisix.md
> docs: update apisix and move to trial

- radar/2024-06-01/vistecture.md
> docs: fade out vistecture

- radar/2024-06-01/rxjava.md
> docs: fade out rxjava

- radar/2024-06-01/graalnative.md
> docs: fade out graal native image

- radar/2024-06-01/temporal-modeling.md
> docs: fade out temporal modeling

- radar/2024-06-01/self-service-infrastructure.md
> docs: fade out Self-Service Infrastructure

- radar/2024-06-01/remix.md
> docs: update remix

- radar/2022-03-28/unleash.md
- radar/2024-06-01/unleash.md
> docs: move unleash to tools and fade out

- radar/2024-06-01/invision.md
Fadeout article to fadeout inVision. I am not sure how to fadeout properly ;/
> docs: V8 invision fadeout

- radar/2024-06-01/angular.md
Adds updated Angular text for Angular 18
Fixes [#289](https://gitlab.aoe.com/shared/aoe/tech-radar-voting/-/issues/289)
> docs: update angular for v18

- radar/2025-05-31/stitches.md
> docs: fade out stitches

- radar/2025-05-31/cypress.md
> docs: fade out cypress

- radar/2024-07-10/panda-css.md
- radar/2025-05-31/lighthouse-ci.md
Changed Lighthouse CI to adopt and faded it out
> docs: adopt and fadeout lhci

- radar/2024-07-10/panda-css.md
- radar/2025-05-31/backstage.md
- radar/2025-05-31/tailwindcss.md
Fade out Backstage and move it to trial
> docs: trial and fadeout backstage

- radar/2024-07-10/panda-css.md
- radar/2025-05-31/adobe-creative-cloud.md
> docs: fadeout adobe creative cloud

- radar/2024-07-10/panda-css.md
- radar/2025-05-31/helm.md
> docs: fadeout helm

- radar/2024-07-10/panda-css.md
- radar/2025-05-31/api-testing.md
Introduce API-Testing within Methods and Patterns
> docs: api testing

- radar/2024-07-10/bun.md
https://gitlab.aoe.com/shared/aoe/tech-radar-voting/-/issues/372
> docs:  move bun to languages and frameworks
